repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
    -   id: go-fmt
    -   id: go-lint
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: ./client/node_modules/.bin/eslint
        language: node
        language_version: system
        files: \.(js|jsx)$
