language: go
go:
    - 1.14.x
env:
    - GO111MODULE=on
notifications:
    email: false
# Use the latest stable version of Node
install:
    - . $HOME/.nvm/nvm.sh
    - nvm install stable
    - nvm use stable
    - npm install
before_install:
    - "cd client"
script:
    # Lint client code
    - "npm run lint || travis_terminate 1"
    # Run server tests
    - "npm run test || travis_terminate 1"
    # Server checks:
    - "cd ../server"
    # Lint server code
    - "diff -u <(echo -n) <(gofmt -d -s .) || travis_terminate 1"
    # Run server tests
    - "go test -v ./..."
# Just run on master branch since we run on PRs
branches:
    only:
        - master
