language: go
go:
    - 1.14.x
env:
    - GO111MODULE=on
notifications:
    email: false
before_script:
script:
    # Lint client code
    - "npm run lint"
    # Run server unit tests
    - "go test -v ./..."
